---
deployment:
  tasks:
    - export DEPLOYPATH=/home/makroz/public_html/gfactura
        - /bin/cp -r -f * $DEPLOYPATH
    - cd  $DEPLOYPATH
    - /bin rm -f .env
    #- /bin/cp -f .env.host .env


