---
deployment:
  tasks:
    - export DEPLOYPATH=/home/makroz/public_html/gfactura
    - cp -r * $DEPLOYPATH
    - cd $DEPLOYPATH
    - rm -f $DEPLOYPATH/.env
    - cp $DEPLOYPATH/.env.host $DEPLOYPATH/.env
